language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-27
  - extra-google-m2repository
  - extra-android-m2repository
before_install:
  - openssl aes-256-cbc -K $encrypted_b1e792349fee_key -iv $encrypted_b1e792349fee_iv
    -in keys.tar.enc -out keys.tar -d
  - tar xvf keys.tar